
name: Etl flow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wfh
        run: python wfh.py


  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wfh3
        run: python wfh2.py

  
    